-- STRING FUNCTIONS
SELECT CONCAT(first_name,' ',last_name) AS FULL_NAME FROM EMPLOYEE;

SELECT UPPER(email) AS UPPER_CASE_EMAIL FROM EMPLOYEE;

-- EXTRACTING THE FIRST 3 CHARACTERS OF THE EMAIL
SELECT SUBSTRING(EMAIL, 1,3) AS EMIAL_PREFIX FROM EMPLOYEE;

SELECT EMAIL, LENGTH(EMAIL) AS EMAIL_LENGTH FROM EMPLOYEE;

SELECT TRIM(department_name) FROM EMPLOYEE;

-- CONVERT EMAIL ADDRESSES TO UPPERCASE AND EXTRACT THE DOMAIN PART
SELECT UPPER(EMAIL) AS UPPER_CASE_EMAIL, SUBSTRING(EMAIL, INSTR(EMAIL,'@')+1) AS EMAIL_DOMAIN
FROM EMPLOYEE;

-- REPLACE 'IT' WITH 'INFORMATION TECHNOLOGY' IN DEPARTMENT NAMES
SELECT department_name, REPLACE(department_name, 'IT', 'INFORMATION TECHNOLOGY')
FROM DEPARTMENT;

-- DATE FUNCTIONS
SELECT CURRENT_DATE() AS CURRENT_DATE;

SELECT first_name, last_name, DATE_FORMAT(hire_date, '%Y-%m-%d') AS hire_date
FROM EMPLOYEE;


-- ADDING 1 MONTH TO THE HIRE DATE
SELECT first_name, last_name, hire_date,
DATE_ADD(hire_date, INTERVAL 1 MONTH) AS HIRE_DATE_PLUS_ONE_MONTH
FROM EMPLOYEE;

-- CALCULATE NUMBER OF MONTHS SINCE PROJECT START DATE
SELECT project_name, start_date,
DATEDIFF(CURRENT_DATE(), start_date)/30 AS MONTHS_SINCE_START
FROM PROJECT;







